services:
  db:
    container_name: postgres
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    ports:
      - 7777:7777

  api:
    container_name: api
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: yarn dev
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ../src:/home/node/app/src
      - ../prisma:/home/node/app/prisma
    env_file:
      - ../.env
    depends_on:
      - db

volumes:
  postgres_data: